// Configuration des projets
// ordre: hackathon, n8n, 42, perso
const projectsConfigData = [
    {
        id: 1,
        title: "Hackathon - 42AI x Blackbox.ai - Agents building Agents - Team(4)",
        objective: "Créer un prototype fonctionnel en utilisant les agents IAs et les solutions de l'entreprise blackbox.ai",
        skills: "Agents AI, Team, prototyping, rush, stress management",
        liked: "Pouvoir construire une application fonctionnelle en connectant différents services entre eux",
        disliked: "Avoir plus de temps pour que l'UI soit plus agréable et connecter les agents IA entre eux",
        image: "img/projet/hackathon-blackbox.png",
        projectLink: "srcs/html/deploy-anything.html",
        githubLink: "https://github.com/shadokan87/Deploy-Anything",
    },
    {
        id: 2,
        title: "42-Linear-Regression",
        objective: "Implémentation d'un modèle de régression linéaire de A à Z pour prédire les prix de voitures en fonction de leur kilométrage.",
        skills: "Python, Machine Learning, Mathématiques, Analyse de données, Visualisation, Testing",
        liked: "Comprendre les fondements mathématiques de la régression linéaire et l’implémenter sans librairies externes.",
        disliked: "La gestion des données manquantes et l’optimisation des hyperparamètres, parfois fastidieuses.",
        image: "img/projet/42-linear-regression.png",
        projectLink: "srcs/html/42-linear-regression.html",
        githubLink: "https://github.com/afuma/42-Linear-Regression",
    },
    {
        id: 3,
        title: "42-Transcendance - Projet d’équipe à 3",
        objective: "Développer une interface complète et fonctionnelle pour un jeu de Pong local, incluant les modes 1vs1, IA, multijoueur, 3D et tournoi, avec authentification utilisateur, menu de jeu, support de trois langues, historique des parties, authentification à deux facteurs (2FA) et personnalisation du profil.",
        skills: "JavaScript, API REST, Django, Documentation, Développement de jeux vidéo, Travail en équipe",
        liked: "La synergie et l’énergie positive du groupe, véritablement stimulantes.",
        disliked: "Le manque de temps pour échanger davantage avec tous les coéquipiers à cause du rythme intense.",
        image: "img/projet/42-transcendance.png",
        projectLink: "srcs/html/42-transcendance.html",
        githubLink: "https://github.com/afuma/42-transcendance",
    },
    {
        id: 4,
        title: "Startup MyVocalApp - Backend",
        objective: "Développer une application fonctionnelle de prise de rendez-vous automatique via un système audio.",
        skills: "Backend, Node.js, NestJS, API Azure, Function Calling, API Google Calendar, Rigueur, Autonomie",
        liked: "Découvrir et utiliser l’architecture claire de NestJS, tout en développant des compétences clés pour le backend.",
        disliked: "Ne pas avoir eu le temps de créer une interface web plus ergonomique et user-friendly.",
        image: "img/projet/tt-startup.png",
        projectLink: "srcs/html/MyVocalApp.html",
        githubLink: "https://github.com/afuma/MyVocalApp",
    },
    {
        id: 5,
        title: "42-Minishell - Projet complet",
        objective: "Réimplémenter de zéro une version fonctionnelle d’un shell Linux.",
        skills: "C Programming, Architecture système, Linux, Shell, Rigueur",
        liked: "Travailler sur un projet concret, proche du monde réel, qui m’a permis de développer de nombreuses compétences techniques.",
        disliked: "Première expérience de travail en groupe : j’ai dû apprendre à m’affirmer et à prendre des décisions pour faire avancer le projet malgré les absences de certains coéquipiers.",
        image: "img/projet/42-minishell.png",
        projectLink: "srcs/html/minishell.html",
        githubLink: "https://github.com/afuma/42-minishell",
    },
    {
        id: 6,
        title: "42-Philosophers - Multithreading",
        objective: "Implémenter la gestion du multithreading à travers le célèbre problème du dîner des philosophes.",
        skills: "C Programming, Multithreading, Synchronisation, Gestion de la concurrence",
        liked: "Comprendre les enjeux de la concurrence et de la synchronisation dans les systèmes multi-threads.",
        disliked: "Les erreurs liées aux conditions de course et aux deadlocks, parfois difficiles à déboguer.",
        image: "img/projet/42-philosopher.png",
        projectLink: "srcs/html/philosophers.html",
        githubLink: "https://github.com/afuma/42-philosopher",
    },
    {
        id: 7,
        title: "42-Inception - Docker",
        objective: "Découvrir et maîtriser Docker en créant une infrastructure virtuelle composée de plusieurs services (Nginx, WordPress, MariaDB, etc.).",
        skills: "Docker, Virtualisation, Réseaux, Sécurité, Automatisation",
        liked: "Approfondir ma compréhension de la conteneurisation et de l’orchestration de services.",
        disliked: "La configuration initiale complexe et parfois chronophage.",
        image: "img/projet/42-inception.png",
        projectLink: "srcs/html/inception.html",
        githubLink: "https://github.com/afuma/42-inception",
    },
    {
        id: 8,
        title: "Kiln Hackathon - Web3 - Team(3)",
        objective: "Implémenter une solution innovante permettant aux utilisateurs de souscrire à une assurance de risque sur une position future, via l’intégration et l’amélioration d’un widget Kiln.",
        skills: "Frontend, Backend, API Integration, Smart Contracts (futures), Finance décentralisée, UX Design, Autonomie",
        liked: "La bienveillance et les explications claires de mon coéquipier, fort de plus de 10 ans d’expérience dans la finance, ainsi que la richesse des échanges avec les autres participants.",
        disliked: "Le manque de temps pour approfondir les aspects blockchain de la solution et pour échanger avec mon coéquipier à cause du rythme intense.",
        image: "img/projet/hackathon-kiln.png",
        projectLink: "srcs/html/kiln-hackathon.html",
        githubLink: "https://github.com/Davphla/kiln-sos",
    },
    {
        id: 9,
        title: "workflow d’automatisation n8n - Youtube vidéos channel extractor",
        objective: "Automatiser la récupération des vidéos d’une chaîne YouTube et centraliser leurs informations (titre, date, vues, likes, description, etc.) dans Google Sheets.",
        skills: "n8n, Automatisation, API YouTube, Google Sheets, Gestion de données",
        liked: "Pouvoir centraliser toutes les informations d’une chaîne automatiquement",
        disliked: "Limiter les quotas API et gérer les erreurs de récupération",
        image: "img/projet/n8n-youtube-video-channel-extractor.png",
        projectLink: "srcs/html/bobo.html",
        githubLink: "https://github.com/afuma/n8n-workflows",
    },
    {
        id: 10,
        title: "workflow d’automatisation n8n - Generate letter motivation for all entreprise",
        objective: "Automatiser l’envoi d’e-mails personnalisés selon des déclencheurs définis, avec suivi des statuts dans un tableau centralisé.",
        skills: "n8n, Automatisation, Email, API, Gestion des flux",
        liked: "Créer un système d’emailing entièrement automatisé",
        disliked: "Gérer les erreurs liées aux API et aux paramètres dynamiques",
        image: "img/projet/n8n-sending-mail.png",
        projectLink: "srcs/html/bobo.html",
        githubLink: "https://github.com/afuma/n8n-workflows",
    },
    {
        id: 11,
        title: "workflow d’automatisation n8n - Generate entire coloring design library",
        objective: "Mettre en place un workflow automatisé pour générer et finaliser des images coloriées à partir de modèles ou templates.",
        skills: "n8n, Automatisation, Image Processing, API",
        liked: "Voir les images se générer automatiquement étape par étape",
        disliked: "Gérer les erreurs dans le traitement d’images et différents formats",
        image: "img/projet/n8n-create-multiple-image-from-image.png",
        projectLink: "srcs/html/bobo.html",
        githubLink: "https://github.com/afuma/n8n-workflows",
    },
    {
        id: 12,
        title: "42-IRC (bonus) - bot de modération",
        objective: "Développer un bot IRC capable de modérer automatiquement les messages, appliquer des sanctions et gérer les utilisateurs du canal.",
        skills: "IRC, C++, Bot Development, Gestion de communauté, Automatisation",
        liked: "Simplifier la modération et protéger la communauté automatiquement",
        disliked: "Gérer les comportements imprévisibles des utilisateurs et les exceptions",
        image: "img/projet/42-irc.png",
        projectLink: "srcs/html/bobo.html",
        githubLink: "https://github.com/afuma/42-IRC",
    },
    {
        id: 13,
        title: "Sudoku Resolver - Backtracking",
        objective: "Développer un solveur de Sudoku intelligent utilisant des algorithmes de backtracking et d'optimisation",
        skills: "Python, Algorithmes, Logique, backtracking, Optimisation",
        liked: "Implémentation d'algorithmes complexes et optimisation des performances",
        disliked: "Debugging de l'algorithme récursif pour le backtracking",
        image: "img/projet/perso-sudoku-solver.png",
        projectLink: "srcs/html/sudoku-resolver.html",
        githubLink: "https://github.com/afuma/sudoku-resolver",
    },
    {
        id: 14,
        title: "42-Solong - Jeu vidéo 2D",
        objective: "Développer un jeu vidéo 2D en se concentrant sur la logique de gameplay et les algorithmes de pathfinding et de gestion des cartes.",
        skills: "C, Algorithme A*, Algorithme flood_fill, Logique de jeu, Gestion de map",
        liked: "Implémenter les algorithmes de pathfinding et optimiser la navigation dans la map a été particulièrement intéressant",
        disliked: "Assurer les performances du moteur de jeu et gérer les collisions de manière efficace",
        image: "img/projet/42-solong.png",
        projectLink: "srcs/html/bobo.html",
        githubLink: "https://github.com/afuma/42-So-Long",
    }
];

// Exposer les données globalement
window.ProjectsConfig = {
    data: projectsConfigData
};
